<a href="https://colab.research.google.com/github/Ryan-spec/Portfolio-Projects/blob/master/Bitcoin_Price_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Bitcoin Price Prediction using Machine Learning and Python



In [2]:
# Import the libraries needed

import pandas as pd
import numpy as np

In [11]:
# Load the data
from google.colab import files
uploaded = files.upload()

Saving datasets_4070_6338_bitcoinP.csv to datasets_4070_6338_bitcoinP.csv


In [12]:
# Store the data into a dataframe and view the first few rows of data
df = pd.read_csv('datasets_4070_6338_bitcoinP.csv')
df.head()

Date    Close
0   3-Oct-17  4317.48
1   2-Oct-17  4409.32
2   1-Oct-17  4403.74
3  30-Sep-17  4338.71
4  29-Sep-17  4163.07

In [13]:
# Remove the date column
df.drop(['Date'], axis = 1, inplace=True)

In [14]:
df.head()

Close
0  4317.48
1  4409.32
2  4403.74
3  4338.71
4  4163.07

In [15]:
# Variable for predicting 'n' days into the future
pred_days = 30 # 'n'= pred_days = 30

# Create another column shifted 'n' units up
df['Prediction'] = df[['Close']].shift(-pred_days)

In [16]:
# Show the first 5 rows of the new dataset
df.head()  

Close  Prediction
0  4317.48     4582.96
1  4409.32     4578.77
2  4403.74     4892.01
3  4338.71     4703.39
4  4163.07     4565.30

In [17]:
# Show the last 5 rows 
df.tail()

Close  Prediction
1615  105.21         NaN
1616  116.99         NaN
1617  139.00         NaN
1618  144.54         NaN
1619  134.21         NaN

In [18]:
# Create the independent dataset

# Convert the dataframe to a numpy array and drop the predictin column
X = np.array(df.drop(['Prediction'], axis=1))

# Remove the last 'n' rows where 'n' is the pred_days
X = X[:len(df)-pred_days]

print(X)

[[4317.48]
 [4409.32]
 [4403.74]
 ...
 [ 128.8 ]
 [ 132.3 ]
 [ 129.  ]]


In [20]:
# Create the dependent dataset

# Convert the dataframe to a numpy array
y = np.array(df['Prediction'])

# Get all the values except the last 'n' rows
y = y[:-pred_days]
print(y)

[4582.96 4578.77 4892.01 ...  139.    144.54  134.21]


In [21]:
# Split the data into 80% training and 20% testing 
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [22]:
# Set the pred_days_array = to the last 30 rows from the original dataset
pred_days_array = np.array(df.drop(['Prediction'], axis=1))[-pred_days:]
print(pred_days_array)

[[129.75]
 [133.48]
 [131.98]
 [133.2 ]
 [126.7 ]
 [123.89]
 [122.88]
 [122.  ]
 [121.99]
 [123.5 ]
 [123.02]
 [118.76]
 [114.22]
 [111.5 ]
 [117.98]
 [115.  ]
 [115.24]
 [117.2 ]
 [112.67]
 [113.57]
 [111.5 ]
 [112.3 ]
 [115.91]
 [112.5 ]
 [ 97.75]
 [105.21]
 [116.99]
 [139.  ]
 [144.54]
 [134.21]]


In [23]:
# Use SVM to create and train or model

from sklearn.svm import SVR

# Create and train the SVM(Regression) using the Radio Basis Function
svr_rbf = SVR(kernel = 'rbf', C = 1e3, gamma = 0.00001)
svr_rbf.fit(x_train, y_train)

SVR(C=1000.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma=1e-05,
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [24]:
# Test model accuracy

svr_rbf_accuracy = svr_rbf.score(x_test, y_test)
print('svr_rbf accuracy:',svr_rbf_accuracy)

svr_rbf accuracy: 0.8668362484080572


In [26]:
# Print the predicted values 
svm_pred = svr_rbf.predict(x_test)
print(svm_pred)

print()

# Print the actual values
print(y_test)

[ 119.31514524  966.2570781   233.18545374  353.77839805  729.61047313
  683.1520687   106.20432837  380.66894391  574.48194373  103.86378726
  681.42597561  437.77507754  441.86539468  602.35365756  232.18262154
  278.3990199   611.15640248  247.80102002  622.8227039  1020.03494228
 1344.43543739  466.61805621 2251.97988988  609.19722346  997.51470603
  108.35514031  234.13292296  749.22644287  286.08591972  936.2900644
  420.87703978  603.16479806  413.93271641  500.9409265   579.05150396
  242.58419115  399.26053024  613.26098092  379.69567391  242.56297369
 1155.41775328  567.56055069  421.59976514 2149.31509059  239.65952958
  123.11355626  281.16191676  986.92950544  202.51936684  373.31912792
  882.01998284  639.8021766   369.73709083  878.62371075  276.09710512
 1887.07638473  348.64114881  330.22102674  369.32765351  111.23282795
  421.63365302 1709.09878822  581.02646741  365.70811933  446.07085341
  212.34265869  316.39589851  397.77434148  584.3865241   581.80385302
  677.4

In [27]:
# Print the model for the next 'n=30' days
svm_pred = svr_rbf.predict(pred_days_array)
print(svm_pred)

[121.28006913 124.12118424 122.96016937 123.90261377 119.07475654
 117.14210902 116.47157675 115.89801293 115.89155279 116.88165279
 116.5637452  113.87415494 111.28125059 109.87071705 113.40809976
 111.70585116 111.83826944 112.95045868 110.46395131 110.93419785
 109.87071705 110.27412401 112.21231521 110.37647914 104.54144309
 107.04524239 112.82869779 128.59593054 133.38162204 124.6949624 ]


In [28]:
# Print the actual values for the last 30 days
print (df.tail(pred_days))

       Close  Prediction
1590  129.75         NaN
1591  133.48         NaN
1592  131.98         NaN
1593  133.20         NaN
1594  126.70         NaN
1595  123.89         NaN
1596  122.88         NaN
1597  122.00         NaN
1598  121.99         NaN
1599  123.50         NaN
1600  123.02         NaN
1601  118.76         NaN
1602  114.22         NaN
1603  111.50         NaN
1604  117.98         NaN
1605  115.00         NaN
1606  115.24         NaN
1607  117.20         NaN
1608  112.67         NaN
1609  113.57         NaN
1610  111.50         NaN
1611  112.30         NaN
1612  115.91         NaN
1613  112.50         NaN
1614   97.75         NaN
1615  105.21         NaN
1616  116.99         NaN
1617  139.00         NaN
1618  144.54         NaN
1619  134.21         NaN


### Our model has in fact proven to be 86% accurate as can be seen above.